# Copyright 2023 Lawrence Livermore National Security, LLC and other
# Benchpark Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: Apache-2.0

packages:
  all:
    providers:
      mpi:
      - cray-mpich
  lapack:
    externals:
    - spec: openblas@0.3.23
      prefix: /user-environment/env/default/lib
    buildable: false
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.28
      prefix: /user-environment/env/default
